name: Continuous Integration

on:
  push:
    braches:
      -main
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'AdoptOpenJDK'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-kys: |
            ${{runner.os}}-maven-

      - name: Maven build
        run: mvn clean install --no-transfer-progress
   