
name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'MackBike/app/**'
  pull_request:
    branches:
      - main
    paths: 
      - 'MackBike/app/**'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'AdoptOpenJDK'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-kys: |
            ${{runner.os}}-maven-

      - name: Maven build
        run: mvn clean install --no-transfer-progress
      
      - name: Run tests
        run: mvn test
        
  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - name: Build Flutter web
        run: flutter build web

   
